In [1]:
import numpy as np

In [43]:
board = np.load('../sample_board.npy')

known_mines = set()
known_safe = set()

for edges in np.argwhere(board>0):
    row,col = edges[0],edges[1]
    
    total_open = []
    for dx in range(-1,2):
        for dy in range(-1,2):
            drow, dcol = row+dy, col+dx
            if drow<0 or drow>board.shape[0] or dcol<0 or dcol>board.shape[1]:
                continue
            if board[drow,dcol] == -1:
                total_open.append((drow,dcol))                  
    
    if len(total_open) == board[row,col]:        
        known_mines.update(total_open[0:int(board[row,col])])

for mines in known_mines:
    board[mines[0],mines[1]] = -3
    
for edges in np.argwhere(board>0):
    row,col = edges[0],edges[1]
    
    total_open = []
    total_mines = 0
    for dx in range(-1,2):
        for dy in range(-1,2):
            drow, dcol = row+dy, col+dx
            if drow<0 or drow>board.shape[0] or dcol<0 or dcol>board.shape[1]:
                continue
            if board[drow,dcol] == -1:
                total_open.append((drow,dcol))
            elif board[drow,dcol] == -3:
                total_mines +=1                
                
    if total_mines == board[row,col]:
        known_safe.update(total_open)

print("Mines:",known_mines)              
print("Safe:",known_safe)                
print(board)
# for edges in np.argwhere(board>0):
#     row,col = edges[0],edges[1]
    


# print(known_mines)

Mines: {(7, 3), (6, 7), (3, 3), (3, 0), (3, 1), (0, 6)}
Safe: {(3, 2), (8, 3), (6, 8), (9, 3), (7, 7), (0, 7), (9, 4), (9, 5), (0, 8)}
[[-1. -1.  1. -2. -2.  1. -3. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -2. -2.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  3.  1.  1. -2. -2. -2.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-3. -3. -1. -3.  1. -2. -2. -2.  2. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 2.  2.  2.  1.  1. -2. -2. -2.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-2. -2. -2. -2. -2. -2.  1.  1.  2. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-2. -2.  1.  1.  1. -2.  1. -3. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-2. -2.  1. -3.  1. -2.  2. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-2. -2.  1. -1.  1.  1.  2. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1.  2.  2. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1